language: php

php:
  - 7.0
  - 7.1

directories:
  - $HOME/.composer/cache/files

before_install:
  - npm install -g git+https://github.com/hoten/UglifyJS2#118f14

install:
  - travis_retry composer install

script:
  - mkdir -p build/logs
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
